### ISSUE TITLE
Be able to specify labels for no selection

### ISSUE THREAD

**Issue by ponyta** [b1lly/gumi#7]
Often, a developer will want the select box to be labeled something like "Please select an option...", but not actually have that as an option. The developer should also be able to specify a value for "no selection", since often they might want to grab it for validation.

I think this interface might work:

``` html
<div class="gumi">
  <li class="label" data-value="no selection">Please select an option...</li>
  <ul>
    <li data-value="1">option 1</li>
    .... more options here
  </ul>
</div>
```

Where the "no selection label" should behave similarly when data-value is specified.

**Comment by ponyta** [comment]
On second thought I think it would be better to implement a selectable attribute that determines if an option will appear in the dropdown or not. Then this functionality could then be implemented this way:

``` html
<div class="gumi">
  <ul>
    <li data-value="0" data-selectable="false" data-selected="true">Please select an option</li>
    <li data-value="1">option 1</li>
   ...more options
  </ul>
</div>
```

**Comment by ponyta** [comment]
Never mind, this behaviour is easily replicable this way:

``` html
<div class="gumi">
  <ul>
    <li data-value="0" style="display: none;">Please select an option</li>
    <li data-value="1">option 1</li>
   ...more options
  </ul>
</div>
```

**Comment by b1lly** [comment]
Hey, 

So currently, your last solution is one way to accomplish this. The other, more optimal solution (because it avoids FOUC issues on more dense pages), is to set the button value and use the data-default-value="true" option. 

Also, based on your suggestion, to support the <select> native behavior, setting data-selectable"false" on the first list item with a data-value="null" allows you to give the default option a custom value without it being visible to the user for selection. See https://github.com/b1lly/gumi/commit/7ef9ea05efeac8f5aae855804d8c1dc966f0146c

e.g.

``` html
<div class="gumi">
  <button data-default-value="true">Please select an option</button>
  <ul>
    <li data-value="null" data-selectable="false">Please select an option</li>
    <li data-value="1">option 1</li>
    <li data-value="2">option 2</li>
  </ul>
</div>
```
